# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e9a7c1cbb7b999ffc22526af8ae1eac59a7ee0b23b8e73ab60962f4d437995aee8b0c5f478fb60145700612af4fe4cec31bcd3d336bb934848dd638a492d1ff

test:
  secret_key_base: 0bfa863dfb43bfe6efb0c67a6d554a9d14ec261407abef43ba3bc04496293d46611fcc182b64269d53608901dd3d635519b06e30c01bdd47fa57bed0dd3770a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
